### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by negi111111** [tabsun/MaskRCNN_iOS#1]
nice work

I want to execute your code. 
Is it possible to publish your pre-trained models?

```
#import "depth_unpool1.h"
#import "depth_unpool2.h"
#import "depth_unpool3.h"
#import "depth_unpool4.h"
#import "depth_final_conv.h"
#import "scene_segment.h"
#import "mask_class_box.h"
#import "mask_branch_noalign.h"
#import "mask_rpn.h"
```

**Comment by tabsun** [comment]
Much thanks. This repo is messy by now I will rearrange it soon including the model training / conversion / usage. These are in my working list but no time line. :)

**Comment by negi111111** [comment]
I'm sorry for my late reply.

So please tell me about the following:

How did you make a `.h` file? I think that you convert weights trained by the framework (ex. [tensorflow implementation](https://github.com/matterport/Mask_RCNN)) into `.h` files, what about it?

**Comment by negi111111** [comment]
![寿司ゆき:help](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/11.png)

**Comment by tabsun** [comment]
You can refer to apple's [coreMLTools](https://github.com/apple/coremltools)

**Comment by negi111111** [comment]
I know coreml.
usually i think that .mlmodel will be output.
Are you using any options to output .h files?

**Comment by negi111111** [comment]
OK. Tank.
