### ISSUE TITLE
Can not open the xcodeproj, because it is missing its project.pbxproj file.

### ISSUE THREAD

**Issue by ldbfrank** [tabsun/MaskRCNN_iOS#2]
Git clone the MaskRCNN_iOS, but can't open the xcodeproj, xcode displays it is missing its project.pbxproj file. 
And there isn't a project.pbxproj file in the DPFruit.xcodeproj package.
Why?

**Comment by tabsun** [comment]
I have added that file. Last commit removed it by mistake.
